version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: test-postgres
    environment:
      - POSTGRES_DB=accessibility_scanner_test
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d accessibility_scanner_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: test-redis
    command: redis-server --requirepass test_redis_password
    ports:
      - "6380:6379"
    volumes:
      - redis-test-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-test-data:
  redis-test-data: